use std::collections::BTreeMap;
use std::rc::Rc;

use barsql_core::{ColumnInfo, ConnectionConfig, DriverType, Row, SqlDialect, Value};
use gpui_kit::component::button::{Button, ButtonVariants};
use gpui_kit::component::input::InputState;
use gpui_kit::component::menu::{DropdownMenu, PopupMenu, PopupMenuItem};
use gpui_kit::component::{ActiveTheme, Disableable, Sizable, StyledExt, WindowExt, h_flex, v_flex};
use gpui_kit::prelude::FluentBuilder as _;
use gpui_kit::*;

use crate::form;
use crate::i18n::{t, t_with};
use crate::modal::{self, Modal};
use crate::state;
use crate::tokens::{TEXT_SM, TEXT_XS};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mode {
    Default,
    Null,
    Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Invalid {
    Required,
    NotNullable,
    EmptyInsert,
}

fn starts_with_ignore_case(text: &str, prefix: &str) -> bool {
    text.len() >= prefix.len() && text.as_bytes()[..prefix.len()].eq_ignore_ascii_case(prefix.as_bytes())
}

// Sequences, identities and SQLite's INTEGER PRIMARY KEY rowid alias fill themselves in.
pub fn auto_generated(col: &ColumnInfo, driver: &DriverType) -> bool {
    if col.is_identity || col.is_computed {
        return true;
    }
    if col.default_val.is_empty() {
        let serial = ["serial", "bigserial", "smallserial"].iter().any(|s| starts_with_ignore_case(&col.data_type, s));
        let rowid_alias = driver.dialect() == Some(SqlDialect::Sqlite);
        return (col.is_primary && serial)
            || (rowid_alias && col.is_primary && col.data_type.eq_ignore_ascii_case("integer"));
    }
    let default = col.default_val.to_lowercase();
    ["nextval(", "autoincrement", "auto_increment", "generated always", "generated by default"]
        .iter()
        .any(|marker| default.contains(marker))
}

fn has_default(col: &ColumnInfo, driver: &DriverType) -> bool {
    auto_generated(col, driver) || !col.default_val.trim().is_empty()
}

pub fn requires_value(col: &ColumnInfo, driver: &DriverType) -> bool {
    !auto_generated(col, driver) && !col.is_nullable && !has_default(col, driver)
}

pub fn can_default(col: &ColumnInfo, driver: &DriverType) -> bool {
    has_default(col, driver) || col.is_nullable
}

pub fn initial_mode(col: &ColumnInfo, driver: &DriverType) -> Mode {
    if has_default(col, driver) || col.is_nullable { Mode::Default } else { Mode::Value }
}

pub fn default_hint(col: &ColumnInfo, driver: &DriverType) -> String {
    let default = col.default_val.trim();
    if auto_generated(col, driver) {
        return if default.is_empty() { col.data_type.clone() } else { default.to_string() };
    }
    let chars: Vec<char> = default.chars().collect();
    if chars.len() > 72 { format!("{}…", chars[..72].iter().collect::<String>()) } else { default.to_string() }
}

pub fn validate(
    columns: &[ColumnInfo],
    fields: &BTreeMap<String, (Mode, String)>,
    driver: &DriverType,
) -> Option<Invalid> {
    let mut included = 0;
    for col in columns {
        let Some((mode, value)) = fields.get(&col.name) else { continue };
        if auto_generated(col, driver) {
            continue;
        }
        match mode {
            Mode::Default => {
                if !can_default(col, driver) || requires_value(col, driver) {
                    return Some(Invalid::Required);
                }
            }
            Mode::Null => {
                included += 1;
                if !col.is_nullable {
                    return Some(Invalid::NotNullable);
                }
            }
            Mode::Value => {
                included += 1;
                if value.trim().is_empty() && requires_value(col, driver) {
                    return Some(Invalid::Required);
                }
            }
        }
    }
    (included == 0).then_some(Invalid::EmptyInsert)
}

pub fn payload(columns: &[ColumnInfo], fields: &BTreeMap<String, (Mode, String)>, driver: &DriverType) -> Row {
    columns
        .iter()
        .filter(|col| !auto_generated(col, driver))
        .filter_map(|col| match fields.get(&col.name)? {
            (Mode::Default, _) => None,
            (Mode::Null, _) => Some((col.name.clone(), Value::Null)),
            (Mode::Value, value) => Some((col.name.clone(), Value::Text(value.clone()))),
        })
        .collect()
}

type OnInserted = Rc<dyn Fn(&mut Window, &mut App)>;

pub struct InsertRowForm {
    connection: ConnectionConfig,
    schema: String,
    table: String,
    columns: Vec<ColumnInfo>,
    modes: BTreeMap<String, Mode>,
    inputs: BTreeMap<String, Entity<InputState>>,
    loading: bool,
    saving: bool,
    error: Option<SharedString>,
    invalid: Option<Invalid>,
    on_inserted: OnInserted,
    scroll: ScrollHandle,
}

impl InsertRowForm {
    fn new(
        connection: ConnectionConfig,
        schema: String,
        table: String,
        on_inserted: OnInserted,
        cx: &mut Context<Self>,
    ) -> Self {
        let load = {
            let bar = state::bar(cx);
            let (id, schema, table) = (connection.id.clone(), schema.clone(), table.clone());
            state::spawn(cx, async move { bar.list_columns(&id, &schema, &table).await })
        };
        cx.spawn(async move |this, cx| {
            let result = load.await;
            this.update(cx, |form, cx| {
                form.loading = false;
                match result {
                    Some(Ok(columns)) => form.columns = columns,
                    Some(Err(error)) => form.error = Some(error.message.into()),
                    None => {}
                }
                cx.notify();
            })
            .ok();
        })
        .detach();
        Self {
            connection,
            schema,
            table,
            columns: Vec::new(),
            modes: BTreeMap::new(),
            inputs: BTreeMap::new(),
            loading: true,
            saving: false,
            error: None,
            invalid: None,
            on_inserted,
            scroll: ScrollHandle::new(),
        }
    }

    fn mode(&self, col: &ColumnInfo) -> Mode {
        self.modes.get(&col.name).copied().unwrap_or_else(|| initial_mode(col, &self.connection.driver))
    }

    fn fields(&self, cx: &App) -> BTreeMap<String, (Mode, String)> {
        self.columns
            .iter()
            .map(|col| {
                let value =
                    self.inputs.get(&col.name).map(|input| input.read(cx).value().to_string()).unwrap_or_default();
                (col.name.clone(), (self.mode(col), value))
            })
            .collect()
    }

    fn submit(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let driver = self.connection.driver.clone();
        let fields = self.fields(cx);
        self.invalid = validate(&self.columns, &fields, &driver);
        if self.invalid.is_some() {
            cx.notify();
            return;
        }
        let values = payload(&self.columns, &fields, &driver);
        self.saving = true;
        self.error = None;
        cx.notify();
        let bar = state::bar(cx);
        let (id, schema, table) = (self.connection.id.clone(), self.schema.clone(), self.table.clone());
        let insert = state::spawn(cx, async move { bar.insert_row(&id, &schema, &table, &values).await });
        cx.spawn_in(window, async move |this, cx| {
            let result = insert.await;
            this.update_in(cx, |form, window, cx| {
                form.saving = false;
                match result {
                    Some(Ok(_)) => {
                        window.close_dialog(cx);
                        (form.on_inserted)(window, cx);
                    }
                    Some(Err(error)) => form.error = Some(error.message.into()),
                    None => {}
                }
                cx.notify();
            })
            .ok();
        })
        .detach();
    }

    fn input(&mut self, col: &ColumnInfo, window: &mut Window, cx: &mut Context<Self>) -> Entity<InputState> {
        if let Some(input) = self.inputs.get(&col.name) {
            return input.clone();
        }
        let input = cx.new(|cx| InputState::new(window, cx));
        self.inputs.insert(col.name.clone(), input.clone());
        input
    }

    fn set_mode(&mut self, name: String, mode: Mode, window: &mut Window, cx: &mut Context<Self>) {
        if mode != Mode::Value
            && let Some(input) = self.inputs.get(&name)
        {
            input.update(cx, |state, cx| state.set_value("", window, cx));
        }
        self.modes.insert(name, mode);
        self.invalid = None;
        cx.notify();
    }

    fn field(&mut self, col: ColumnInfo, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let driver = self.connection.driver.clone();
        let mode = self.mode(&col);
        let hidden = auto_generated(&col, &driver);
        let hint = default_hint(&col, &driver);
        let input = self.input(&col, window, cx);
        let placeholder: SharedString = if hidden {
            if hint.is_empty() { t(cx, "tableView.addRowDialog.autoGenerated") } else { hint.clone().into() }
        } else {
            match mode {
                Mode::Default if !hint.is_empty() => hint.clone().into(),
                Mode::Default if col.is_nullable => t(cx, "tableView.addRowDialog.defaultOmitNullable"),
                Mode::Default => t(cx, "tableView.addRowDialog.inputPlaceholderDefault"),
                Mode::Null => t(cx, "tableView.addRowDialog.inputPlaceholderNull"),
                Mode::Value => t(cx, "tableView.addRowDialog.inputPlaceholderValue"),
            }
        };
        input.update(cx, |state, cx| state.set_placeholder(placeholder, window, cx));
        let enabled = !self.saving && !hidden && mode == Mode::Value;
        let theme = cx.theme();
        let badge = |text: SharedString, color: Hsla| form::badge(text, color);
        let mut modes = Vec::new();
        if can_default(&col, &driver) {
            modes.push((Mode::Default, t(cx, "tableView.addRowDialog.modeDefault")));
        }
        if col.is_nullable {
            modes.push((Mode::Null, t(cx, "common.null")));
        }
        modes.push((Mode::Value, t(cx, "tableView.addRowDialog.modeValue")));
        let current = modes.iter().find(|(m, _)| *m == mode).map(|(_, label)| label.clone()).unwrap_or_default();
        let this = cx.entity().downgrade();
        let name = col.name.clone();
        let picker = (!hidden && modes.len() > 1).then(|| {
            form::select_small(SharedString::from(format!("insert-mode-{}", col.name)), current, cx)
                .debug_selector({
                    let selector = format!("insert-mode-{}", col.name);
                    move || selector
                })
                .disabled(self.saving)
                .dropdown_menu(move |mut menu: PopupMenu, _, _| {
                    for (option, label) in modes.clone() {
                        let (this, name) = (this.clone(), name.clone());
                        menu = menu.item(PopupMenuItem::new(label).checked(option == mode).on_click(
                            move |_, window, cx| {
                                this.update(cx, |form, cx| form.set_mode(name.clone(), option, window, cx)).ok();
                            },
                        ));
                    }
                    menu
                })
        });
        let (muted, warning) = (theme.muted_foreground, theme.warning);
        v_flex()
            .gap(rems(0.308))
            .child(
                h_flex()
                    .justify_between()
                    .gap(rems(0.615))
                    .mb(rems(0.154))
                    .child(
                        h_flex()
                            .flex_wrap()
                            .gap(rems(0.385))
                            .min_w_0()
                            .child(div().text_size(TEXT_SM).font_medium().child(col.name.clone()))
                            .child(div().text_size(TEXT_XS).text_color(muted).child(col.data_type.clone())),
                    )
                    .child(
                        h_flex()
                            .flex_none()
                            .gap(rems(0.462))
                            .child(
                                h_flex()
                                    .gap(rems(0.308))
                                    .when(col.is_primary, |el| {
                                        el.child(badge(t(cx, "tableView.addRowDialog.primaryKeyBadge"), muted))
                                    })
                                    .when(col.is_foreign, |el| {
                                        el.child(badge(t(cx, "tableView.addRowDialog.foreignKeyBadge"), muted))
                                    })
                                    .when(requires_value(&col, &driver), |el| {
                                        el.child(badge(t(cx, "tableView.addRowDialog.requiredBadge"), warning))
                                    }),
                            )
                            .children(picker),
                    ),
            )
            .child(
                div()
                    .debug_selector({
                        let selector = format!("insert-field-{}", col.name);
                        move || selector
                    })
                    .child(form::input(&input, window, cx).disabled(!enabled)),
            )
    }
}

impl Render for InsertRowForm {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        let body = if self.loading {
            modal::body().child(div().text_size(TEXT_SM).child(t(cx, "tableView.addRowDialog.loading")))
        } else {
            let message = self.invalid.map(|invalid| match invalid {
                Invalid::Required => t(cx, "tableView.addRowDialog.errorRequired"),
                Invalid::NotNullable => t(cx, "tableView.addRowDialog.errorNotNullable"),
                Invalid::EmptyInsert => t(cx, "tableView.addRowDialog.errorEmpty"),
            });
            let fields: Vec<AnyElement> =
                self.columns.clone().into_iter().map(|col| self.field(col, window, cx).into_any_element()).collect();
            modal::body()
                .children(self.error.clone().map(|error| form::error(error, cx)))
                .children(message.map(|message| form::error(message, cx)))
                .child(v_flex().gap(rems(0.923)).mt(rems(0.615)).children(fields))
        };
        let (loading, saving) = (self.loading, self.saving);
        modal::scroll_content().child(modal::scroll_body(&self.scroll, body)).child(
            modal::footer(cx)
                .child(
                    Button::new("insert-row-cancel")
                        .large()
                        .label(t(cx, "common.cancel"))
                        .disabled(saving)
                        .on_click(|_, window, cx| window.close_dialog(cx)),
                )
                .child(
                    Button::new("insert-row-submit")
                        .large()
                        .debug_selector(|| "insert-row-submit".into())
                        .primary()
                        .label(t(cx, "tableView.addRowDialog.submit"))
                        .disabled(loading || saving || self.columns.is_empty())
                        .on_click(cx.listener(|form, _, window, cx| form.submit(window, cx))),
                ),
        )
    }
}

pub fn open(
    connection: ConnectionConfig,
    schema: String,
    table: String,
    window: &mut Window,
    cx: &mut App,
    on_inserted: impl Fn(&mut Window, &mut App) + 'static,
) {
    let title = t_with(cx, "tableView.addRowDialog.title", &[("table", &table)]);
    let form = cx.new(|cx| InsertRowForm::new(connection, schema, table, Rc::new(on_inserted), cx));
    window.open_dialog(cx, move |dialog, window, cx| {
        Modal::new("insert-row", title.clone()).build(dialog, form.clone(), window, cx).on_ok(|_, _, _| false)
    });
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use barsql_core::{ColumnInfo, DriverType, Row, Value};

    use super::{Invalid, Mode, auto_generated, initial_mode, payload, requires_value, validate};

    fn col(name: &str, data_type: &str, nullable: bool, primary: bool, default: &str) -> ColumnInfo {
        ColumnInfo {
            name: name.into(),
            data_type: data_type.into(),
            is_nullable: nullable,
            is_primary: primary,
            default_val: default.into(),
            ..Default::default()
        }
    }

    fn cols() -> Vec<ColumnInfo> {
        vec![
            col("id", "integer", false, true, "nextval('id_seq'::regclass)"),
            col("email", "varchar", false, false, ""),
            col("note", "text", true, false, ""),
        ]
    }

    #[test]
    fn auto_generated_columns_are_detected_per_driver() {
        let pg = DriverType::Postgres;
        assert!(auto_generated(&cols()[0], &pg));
        assert!(!auto_generated(&cols()[1], &pg));
        let int_pk = col("id", "integer", false, true, "");
        assert!(auto_generated(&int_pk, &DriverType::Sqlite));
        assert!(!auto_generated(&int_pk, &pg) && !auto_generated(&int_pk, &DriverType::MySql));
        assert!(requires_value(&int_pk, &pg));
        assert!(auto_generated(&col("id", "int", false, true, "auto_increment"), &DriverType::MySql));
    }

    #[test]
    fn modes_start_at_the_default_when_there_is_one() {
        let pg = DriverType::Postgres;
        assert_eq!(
            cols().iter().map(|c| initial_mode(c, &pg)).collect::<Vec<_>>(),
            [Mode::Default, Mode::Value, Mode::Default]
        );
        let fk = ColumnInfo { is_foreign: true, ..col("user_id", "integer", true, false, "") };
        assert!(!requires_value(&fk, &pg) && !auto_generated(&fk, &pg));
    }

    #[test]
    fn fields_validate_and_build_the_insert() {
        let pg = DriverType::Postgres;
        let nullable = vec![col("a", "text", true, false, ""), col("b", "text", true, false, "")];
        let initial = |columns: &[ColumnInfo]| -> BTreeMap<String, (Mode, String)> {
            columns.iter().map(|c| (c.name.clone(), (initial_mode(c, &pg), String::new()))).collect()
        };
        assert_eq!(validate(&nullable, &initial(&nullable), &pg), Some(Invalid::EmptyInsert));
        let mut fields = initial(&cols());
        assert_eq!(validate(&cols(), &fields, &pg), Some(Invalid::Required));
        fields.insert("email".into(), (Mode::Value, "a@b.c".into()));
        fields.insert("note".into(), (Mode::Null, String::new()));
        assert_eq!(validate(&cols(), &fields, &pg), None);
        assert_eq!(
            payload(&cols(), &fields, &pg),
            Row::from([("email".into(), Value::Text("a@b.c".into())), ("note".into(), Value::Null)])
        );
        fields.insert("email".into(), (Mode::Null, String::new()));
        assert_eq!(validate(&cols(), &fields, &pg), Some(Invalid::NotNullable));
    }
}
